@startuml
'возведение в степень (с использованием свойства чётности степени).
start
: задать основание и показатель степени<
: результат = 1]
if (показатель != 0) then (да)
  if (показатель по модулю == 1) then (да)
     : результат = основание]
  else (нет)
     while (показатель - четное число) is (да)
       : основание = основание * основание \n показатель = показатель / 2]
     endwhile
     : счетчик = модуль показателя]
     while (счетчик > 0) is (да)
       : результат = результат * основание]
       : счетчик уменьшить на 1]
     endwhile (нет)
  endif
  if (показатель < 0) then (да)
    : результат = 1 / результат]
  endif
endif
: вывести результат>
end
@enduml