@startuml
'получить сумму всех чисел в ряду от 0 до 100 (включительно).
start
: текущий элемент ряда = 0]
: значение суммы = 0]
while (текущий элемент ряда <= 100) is (да)
: значение суммы увеличить \n на текущий элемент ряда]
: текущий элемент ряда \n увеличить на 1]
endwhile (нет)
: вывести значение суммы>
end
@enduml